### ISSUE TITLE
Handle client errors using exceptions

### ISSUE THREAD

**Issue by f-lopes** [quasarch/akash-java#6]
Regarding this open question: https://github.com/quasarch/akash-java/blob/f19df34c6f1ede24ef2936727541c33ad6afa509/src/main/java/cloud/quasarch/akash/impl/Akash.java#L22

In my opinion, the Java client, unlike Go's one, should use exceptions to handle client errors.

For example, a failure to retrieve active deployments should throw an `AkashClientException`  (or a more specific exception).

**Comment by GoncaloPT** [comment]
Hello @f-lopes. 
Thanks for your question and for spotting some leftovers 😄 

I will take the opportunity to justify this option:
The option to stick with the Either - exceptionless - was based on two thoughts:
- We want to give the have the option of not using exceptions since many of us see them as fancy gotos. As you are aware, gotos break the control flow and we wanted to avoid that.
- The contract/implementation of this "exceptionless" approach allows clients ( or even us as lib developers ) to easily plug in a facade implementation that introduces Runtime exceptions or even a Decorator which introduces CheckedExceptions.

With this being said, feel free to open a PR with the implementation of such a Decorator. 👍🏼
